### ISSUE TITLE
add ORCIDs

### ISSUE THREAD

**Issue by danielskatz** [proycon/codemetapy#2]
It would be nice if this added ORCIDs, or at least a placeholder for them to be filled in manually later

**Comment by proycon** [comment]
Right, I just implemented a ``-with-orcid`` parameter that generates placeholders. Is this what you were looking for?

**Comment by danielskatz** [comment]
It sounds like it - but I won't have a chance to try it soon

**Comment by proycon** [comment]
No problem, I released the new version in the meantime.
