### ISSUE TITLE
Context parsed wrong?

### ISSUE THREAD

**Issue by broeder-j** [proycon/codemetapy#32]
Currently codemetapy often generates a context for the jsonLD like this:
```
    "@context": [
        "https://raw.githubusercontent.com/codemeta/codemeta/2.0/codemeta.jsonld",
        "https://raw.githubusercontent.com/schemaorg/schemaorg/main/data/releases/13.0/schemaorgcontext.jsonld",
        "https://w3id.org/software-types",
        "https://w3id.org/software-iodata"
    ],
```

While codemeta does expect a context like this:
```
"@context": "https://doi.org/10.5063/schema/codemeta-2.0",
```

Is there any good reason for the first context list? 
I know that usual context can be nested and complex and codemeta.json would do well to allow for easy extensions or embeding.
While it does not, the harvester should put the right context in my opinion, at least the right reference to the codemeta schema.

**Comment by proycon** [comment]
I had some issues where doi.org didn't properly work at the time, but I agree it would be better to put the doi.org URL in there (and schema.org). I'll try if it works now.
