### ISSUE TITLE
Feature request: codemetapy does not extract maintainer from package.json or pyproject.toml

### ISSUE THREAD

**Issue by apirogov** [proycon/codemetapy#44]
`package.json` has a `maintainers` list, also both the PEP-compliant and poetry-based `pyproject.toml` have support to list project maintainers, which is quite important information.

codemeta apparently also has a `maintainer` field: https://codemeta.github.io/user-guide/

Would be nice if it would use e.g. the first maintainer from the list and add as the codemeta (don't know what codemeta allows, but actually being able to list all maintainers would be even better).

**Comment by proycon** [comment]
Agreed, these should be used, and multiple maintainers are possible.

**Comment by proycon** [comment]
Implemented and released (v2.5.1)
